In [1]:
import numpy as np

def initialize_weights(input_dim):
    """Initialize weights to ones (fully active memory traces)."""
    return np.ones(input_dim)

def calculate_similarity(input_pattern, weights):
    """Compute similarity between input pattern and weight vector."""
    return np.sum(np.minimum(input_pattern, weights)) / np.sum(input_pattern)

def update_weights(input_pattern, weights):
    """Update weights using the ART1 learning rule: w_new = min(input, w_old)."""
    return np.minimum(input_pattern, weights)

def ART_neural_network(input_patterns, vigilance):
    """Adaptive Resonance Theory (ART1) clustering algorithm."""
    num_patterns, input_dim = input_patterns.shape
    categories = []  # Stores category weight vectors

    for pattern in input_patterns:
        matched_category = None

        # Try to find a matching category
        for category in categories:
            if calculate_similarity(pattern, category["weights"]) >= vigilance:
                matched_category = category
                break

        # If no matching category found, create a new one
        if matched_category is None:
            new_weights = initialize_weights(input_dim)
            matched_category = {"weights": new_weights, "patterns": []}
            categories.append(matched_category)

        # Update category with new pattern
        matched_category["patterns"].append(pattern)
        matched_category["weights"] = update_weights(pattern, matched_category["weights"])

    return categories

# Example usage
input_patterns = np.array([
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 0, 1, 1]
])
vigilance = 0.5

categories = ART_neural_network(input_patterns, vigilance)

# Print the learned categories
for i, category in enumerate(categories):
    print(f"Category {i+1}:")
    print("Patterns:")
    for pattern in category["patterns"]:
        print(pattern)
    print("Weights:")
    print(category["weights"])
    print()


Category 1:
Patterns:
[1 0 1 0]
[1 1 1 0]
[1 0 1 1]
Weights:
[1. 0. 1. 0.]

Category 2:
Patterns:
[0 1 0 1]
Weights:
[0. 1. 0. 1.]

